/* Generated By:JavaCC: Do not edit this line. BibTeXConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BibTeXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARTICLE = 5;
  /** RegularExpression Id. */
  int BOOK = 6;
  /** RegularExpression Id. */
  int BOOKLET = 7;
  /** RegularExpression Id. */
  int CONFERENCE = 8;
  /** RegularExpression Id. */
  int INBOOK = 9;
  /** RegularExpression Id. */
  int INCOLLECTION = 10;
  /** RegularExpression Id. */
  int INPROCEEDINGS = 11;
  /** RegularExpression Id. */
  int MANUAL = 12;
  /** RegularExpression Id. */
  int MASTERTHESIS = 13;
  /** RegularExpression Id. */
  int MISC = 14;
  /** RegularExpression Id. */
  int PHDTHESIS = 15;
  /** RegularExpression Id. */
  int PROCEEDINGS = 16;
  /** RegularExpression Id. */
  int TECHREPORT = 17;
  /** RegularExpression Id. */
  int UNPUBLISHED = 18;
  /** RegularExpression Id. */
  int AUTHOR = 19;
  /** RegularExpression Id. */
  int TITLE = 20;
  /** RegularExpression Id. */
  int JOURNAL = 21;
  /** RegularExpression Id. */
  int YEAR = 22;
  /** RegularExpression Id. */
  int VOLUME = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;
  /** RegularExpression Id. */
  int PAGES = 25;
  /** RegularExpression Id. */
  int MONTH = 26;
  /** RegularExpression Id. */
  int NOTE = 27;
  /** RegularExpression Id. */
  int KEY = 28;
  /** RegularExpression Id. */
  int EDITOR = 29;
  /** RegularExpression Id. */
  int PUBLISHER = 30;
  /** RegularExpression Id. */
  int SERIES = 31;
  /** RegularExpression Id. */
  int ADDRESS = 32;
  /** RegularExpression Id. */
  int EDITION = 33;
  /** RegularExpression Id. */
  int HOWPUBLISHED = 34;
  /** RegularExpression Id. */
  int CHAPTER = 35;
  /** RegularExpression Id. */
  int TYPE = 36;
  /** RegularExpression Id. */
  int BOOKTITLE = 37;
  /** RegularExpression Id. */
  int ORGANIZATION = 38;
  /** RegularExpression Id. */
  int SCHOOL = 39;
  /** RegularExpression Id. */
  int INSTITUTION = 40;
  /** RegularExpression Id. */
  int CHARACTER = 41;
  /** RegularExpression Id. */
  int WORD = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"@article\"",
    "\"@book\"",
    "\"@booklet\"",
    "\"@conference\"",
    "\"@inbook\"",
    "\"@incollection\"",
    "\"@inproceedings\"",
    "\"@manual\"",
    "\"@masterthesis\"",
    "\"@misc\"",
    "\"@phdthesis\"",
    "\"@proceedings\"",
    "\"@techreport\"",
    "\"@unpublished\"",
    "\"author\"",
    "\"title\"",
    "\"journal\"",
    "\"year\"",
    "\"volume\"",
    "\"number\"",
    "\"pages\"",
    "\"month\"",
    "\"note\"",
    "\"key\"",
    "\"editor\"",
    "\"publisher\"",
    "\"series\"",
    "\"address\"",
    "\"edition\"",
    "\"howpublished\"",
    "\"chapter\"",
    "\"type\"",
    "\"booktitle\"",
    "\"organization\"",
    "\"school\"",
    "\"institution\"",
    "<CHARACTER>",
    "<WORD>",
    "\"{\"",
    "\",\"",
    "\"\\\'\"",
    "\"=\"",
    "\"\\\"\"",
  };

}
